export const images = {
  yourlogo: "/assets/yourlogo.svg",
  brainwave: "/assets/sciper_loho.png",
  check: "/assets/check.svg",
  check2: "/assets/check-02.svg",
  loading1: "/assets/loading-01.svg",
  brainwaveSymbol: "/assets/scriper_logo.png",
  brainwaveWhiteSymbol: "/assets/scriper_logo.png",
  play: "/assets/play.svg",
  gradient: "/assets/gradient.png",
  smallSphere: "/assets/4-small.png",
  grid: "/assets/grid.png",
  homeSmile: "/assets/home-smile.svg",
  file02: "/assets/file-02.svg",
  searchMd: "/assets/search-md.svg",
  plusSquare: "/assets/plus-square.svg",
  recording03: "/assets/recording-03.svg",
  recording01: "/assets/recording-01.svg",
  disc02: "/assets/disc-02.svg",
  chromecast: "/assets/chrome-cast.svg",
  sliders04: "/assets/sliders-04.svg",
  loading: "/assets/loading.png",
  background: "/assets/background.jpg",
  curve: "/assets/hero/curve.png",
  robot: "/assets/hero/robot.jpg",
  heroBackground: "/assets/hero/hero-background.jpg",
  curve1: "/assets/collaboration/curve-1.svg",
  curve2: "/assets/collaboration/curve-2.svg",
  discord: "/assets/collaboration/discord.png",
  ig: "/assets/collaboration/ig.jpeg",
  shopee: "/assets/collaboration/shopee nbw.jpeg",
  notion: "/assets/collaboration/notion.png",
  youtube: "/assets/collaboration/yt.png",
  tokped: "/assets/collaboration/tokped.jpeg",
  fb: "/assets/collaboration/fb.jpeg",
  shopee_bw: "/assets/collaboration/shopee.jpeg",
  youtube_bw: "/assets/collaboration/youtube.jpeg",
  tokped_bw: "/assets/collaboration/tokped bw.jpeg",
  tiktok: "/assets/collaboration/tiktok.jpeg",
  service1: "/assets/services/service-1.png",
  service2: "/assets/services/service-2.png",
  service3: "/assets/services/service-3.png",
  lines: "/assets/pricing/lines.svg",
  stars: "/assets/pricing/stars.svg",
  coins: "/assets/roadmap/coins.png",
  done: "/assets/roadmap/done.svg",
  hero: "/assets/roadmap/hero.png",
  roadmap1: "/assets/roadmap/image-1.png",
  roadmap2: "/assets/roadmap/image-2.png",
  roadmap3: "/assets/roadmap/image-3.png",
  roadmap4: "/assets/roadmap/image-4.png",
  undone: "/assets/roadmap/undone.svg",
  notification1: "/assets/notification/image-1.png",
  notification2: "/assets/notification/image-2.png",
  notification3: "/assets/notification/image-3.png",
  notification4: "/assets/notification/image-4.png",
  benefitCard1: "/assets/benefits/card-1.svg",
  benefitCard2: "/assets/benefits/card-2.svg",
  benefitCard3: "/assets/benefits/card-3.svg",
  benefitCard4: "/assets/benefits/card-4.svg",
  benefitCard5: "/assets/benefits/card-5.svg",
  benefitCard6: "/assets/benefits/card-6.svg",
  benefitIcon1: "/assets/benefits/icon-1.svg",
  benefitIcon2: "/assets/benefits/icon-2.svg",
  benefitIcon3: "/assets/benefits/icon-3.svg",
  benefitIcon4: "/assets/benefits/icon-4.svg",
  benefitImage2: "/assets/benefits/image-2.png",
  discordBlack: "/assets/socials/discord.svg",
  facebook_bw: "/assets/socials/facebook.svg",
  instagram_bw: "/assets/socials/instagram.svg",
  telegram: "/assets/socials/telegram.svg",
  twitter: "/assets/socials/twitter.svg",
  X: "/assets/collaboration/X.jpeg"
};

const {
  yourlogo,
  homeSmile,
  file02,
  searchMd,
  plusSquare,
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
  discord,
  ig,
  instagram_bw,
  fb,
  facebook_bw,
  youtube,
  youtube_bw,
  shopee,
  shopee_bw,
  tokped,
  tokped_bw,
  notion,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  notification2,
  notification3,
  notification4,
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  discordBlack,
  telegram,
  twitter,
  tiktok,
  X,
} = images;

export const navigation = [
  {
    id: "0",
    title: "Features",
    url: "#features",
  },
  {
    id: "1",
    title: "Pricing",
    url: "#pricing",
  },
  {
    id: "2",
    title: "How to use",
    url: "#how-to-use",
  },
  {
    id: "3",
    title: "Roadmap",
    url: "#roadmap",
  },
  {
    id: "4",
    title: "Register",
    url: "#pricing",
    onlyMobile: true,
  },
  // {
  //   id: "5",
  //   title: "Sign in",
  //   url: "#pricing",
  //   onlyMobile: true,
  // },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [instagram_bw, youtube_bw, tiktok, facebook_bw, X];

export const brainwaveServices = ["Photo generating", "Photo enhance", "Seamless Integration"];

export const brainwaveServicesIcons = [recording03, recording01, disc02, chromecast, sliders04];

export const roadmap = [
  {
    id: "0",
    title: "Voice recognition",
    text: "Enable the chatbot to understand and respond to voice commands, making it easier for users to interact with the app hands-free.",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: "1",
    title: "Gamification",
    text: "Add game-like elements, such as badges or leaderboards, to incentivize users to engage with the chatbot more frequently.",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap2,
  },
  {
    id: "2",
    title: "Chatbot customization",
    text: "Allow users to customize the chatbot's appearance and behavior, making it more engaging and fun to interact with.",
    date: "May 2023",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "3",
    title: "Integration with APIs",
    text: "Allow the chatbot to access external data sources, such as weather APIs or news APIs, to provide more relevant recommendations.",
    date: "May 2023",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "With smart automation and top-notch security, it's the perfect solution for teams looking to work smarter.";

export const collabContent = [
  {
    id: "0",
    title: "Seamless Integration",
    text: collabText,
  },
  {
    id: "1",
    title: "Smart Automation",
  },
  {
    id: "2",
    title: "Top-notch Security",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "Instagram",
    icon: ig,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "Youtube",
    icon: youtube,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Tiktok",
    icon: tiktok,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "Shopee",
    icon: shopee,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "Tokopedia",
    icon: tokped,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "Facebook",
    icon: fb,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Discord",
    icon: discord,
    width: 26,
    height: 34,
  },
  {
    id: "7",
    title: "X",
    icon: X,
    width: 38,
    height: 32,
  },
];

export const pricing = [
  {
    id: "0",
    title: "Free Plan",
    description: "0 Credit",
    price: "0",
    features: [
      "An AI that can understand your video",
      "Basic script generation for personal projects.",
      "Basic background music, and voiceovers generation.",
      "Ability to explore the app and its features without any cost",
    ],
  },
  {
    id: "1",
    title: "Pro Plan",
    description: "450 credits / months. Advanced generative AI, priority support",
    price: "49.99",
    features: [
      "All features from Free Plan",
      "Advance sound effects, background music, and voiceovers generation.",
      "Video advertisements and product photography (image enhancer) creation.",
      "AI assistent for social media manager (content creation and promotion).",
      "Priority support to solve issues quickly",
    ],
  },
  {
    id: "2",
    title: "Enterprise",
    description: "Custom amount of Scriper AI service, advanced analytics.",
    price: null,
    features: [
      "All features from Pro Plan",
      "Custom generative AI model based on your preferences",
      "High Priority on content creation",
    ],
  },
];

export const benefits = [
  {
    id: "0",
    title: "Effortless Script Generation",
    text: "Scriper generates voiceovers and scripts that perfectly fit your video or topic of interest.",
    backgroundUrl: "assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "1",
    title: "Automated Ad Creation",
    text: "Simply upload a product image and information, and let Scriper create high-quality ads for you—no matter the original image quality.",
    backgroundUrl: "assets/benefits/card-2.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "Stay Ahead of Trends",
    text: "Our unique technique ensures that your content stays fresh and follows the latest market trends.",
    backgroundUrl: "assets/benefits/card-3.svg",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  {
    id: "3",
    title: "Seamless Sound Integration",
    text: "Add sound effects, background music, and voiceovers effortlessly to your videos.",
    backgroundUrl: "assets/benefits/card-4.svg",
    iconUrl: benefitIcon4,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "4",
    title: "Product Image Enhancer",
    text: "Improve the quality of product images for high-quality ad generation.",
    backgroundUrl: "assets/benefits/card-5.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
  },
  {
    id: "5",
    title: "Social Media Integration",
    text: "Scriper can handle company social media to gradually content for your product on the best time.",
    backgroundUrl: "assets/benefits/card-6.svg",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
  },
];

export const socials = [
  {
    id: "0",
    title: "Discord",
    iconUrl: discordBlack,
    url: "#",
  },
  {
    id: "1",
    title: "Twitter",
    iconUrl: twitter,
    url: "#",
  },
  {
    id: "2",
    title: "Instagram",
    iconUrl: instagram_bw,
    url: "#",
  },
  {
    id: "3",
    title: "Telegram",
    iconUrl: telegram,
    url: "#",
  },
  {
    id: "4",
    title: "Facebook",
    iconUrl: facebook_bw,
    url: "#",
  },
];
